name: snake
version: 0.1.0.0
github: "dustinrohde/snake"
license: BSD3
author: "Dustin Rohde"
maintainer: "dustin.rohde@gmail.com"
copyright: "2021 Dustin Rohde"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/dustinrohde/snake#readme>

dependencies:
  - base >= 4.7 && < 5
  - brick == 0.52.1
  - containers == 0.6.2.1
  - extra == 1.7.9
  - lens == 4.18.1
  - linear == 1.21.3
  - random == 1.1
  - transformers
  - vty == 5.28.2

library:
  source-dirs: src

executables:
  snake-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - snake
